Artefakt/urls.py
#   Copyright © 2024 Tobias Mieves
#  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pm2sim.urls")),
]

pm2sim/urls.py
#   Copyright © 2024 Tobias Mieves
#  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
from django.conf.urls.static import static
from django.urls import path

from Artefakt import settings
from pm2sim import views

urlpatterns = [
    path("", views.home_view, name="home_view"),
    path("eventLogs", views.EventLogListView.as_view(), name="eventlogList"),
    path(
        "eventLogs/new", views.EditOrCreateEventLogView.as_view(), name="createEventLog"
    ),
    path(
        "eventLogs/<uuid:pk>", views.EventLogDetailView.as_view(), name="eventlogDetail"
    ),
    path(
        "eventLogs/<uuid:pk>/delete",
        views.DeleteEventLogView.as_view(),
        name="deleteEventLog",
    ),
    path(
        "eventLogs/<uuid:pk>/analyse/original",
        views.generate_event_log_data,
        name="analyseEventLog",
    ),
    path("eventLogs/<uuid:pk>/simulate", views.simulate, name="simulateEventLog"),
    path(
        "eventLogs/<uuid:event_log_pk>/analyse/simulated/<int:simulation_run_id>",
        views.analyse_simulated_event_log,
        name="analyseSimulatedEventLog",
    ),
    path(
        "simulationRun/<int:pk>/delete",
        views.DeleteSimulationRunView.as_view(),
        name="deleteSimulationRun",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pm2sim/models.py
#   Copyright © 2024 Tobias Mieves
#  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import uuid

from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse


class EventLog(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=500)
    file = models.FileField(
        upload_to="event-logs/",
        validators=[FileExtensionValidator(allowed_extensions=["xes", "csv"])],
    )
    start_activities = models.CharField(max_length=5000, null=True, blank=True)
    end_activities = models.CharField(max_length=5000, null=True, blank=True)
    number_of_cases = models.IntegerField(null=True, blank=True)
    process_img = models.ImageField(upload_to="process_images/", null=True, blank=True)

    def get_absolute_url(self):
        return reverse("eventlogDetail", kwargs={"pk": self.id})


class SimulationRun(models.Model):
    event_log = models.ForeignKey(EventLog, on_delete=models.CASCADE)
    start_time_mean_o = models.FloatField(null=True, blank=True)
    start_time_std_o = models.FloatField(null=True, blank=True)
    start_time_mean_s = models.FloatField(null=True, blank=True)
    start_time_std_s = models.FloatField(null=True, blank=True)
    simulated_process_img = models.ImageField(
        upload_to="simulated_process_images/", null=True, blank=True
    )
    simulated_event_log = models.FileField(
        upload_to="generated_logs/", null=True, blank=True
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    duration = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ("-timestamp",)


class EventTime(models.Model):
    name = models.CharField(max_length=5000)
    mean_time_o = models.FloatField(null=True, blank=True)
    std_deviation_o = models.FloatField(null=True, blank=True)
    mean_time_s = models.FloatField(null=True, blank=True)
    std_deviation_s = models.FloatField(null=True, blank=True)
    simulation_run = models.ForeignKey(
        to=SimulationRun, related_name="event_times", on_delete=models.CASCADE
    )


class EvaluationResults(models.Model):
    simulation_run = models.ForeignKey(
        to=SimulationRun, related_name="evaluation_results", on_delete=models.CASCADE
    )
    tr_sim_log_on_orig_mod_precision = models.FloatField(null=True, blank=True)
    tr_sim_log_on_orig_mod_perc_fit_traces = models.FloatField(null=True, blank=True)
    tr_sim_log_on_orig_mod_av_trace_fitness = models.FloatField(null=True, blank=True)
    tr_orig_log_on_sim_mod_precision = models.FloatField(null=True, blank=True)
    tr_orig_log_on_sim_mod_perc_fit_traces = models.FloatField(null=True, blank=True)
    tr_orig_log_on_sim_mod_av_trace_fitness = models.FloatField(null=True, blank=True)

    al_sim_log_on_orig_mod_precision = models.FloatField(null=True, blank=True)
    al_sim_log_on_orig_mod_perc_fit_traces = models.FloatField(null=True, blank=True)
    al_sim_log_on_orig_mod_av_trace_fitness = models.FloatField(null=True, blank=True)
    al_orig_log_on_sim_mod_precision = models.FloatField(null=True, blank=True)
    al_orig_log_on_sim_mod_perc_fit_traces = models.FloatField(null=True, blank=True)
    al_orig_log_on_sim_mod_av_trace_fitness = models.FloatField(null=True, blank=True)


class EventChangeStat(models.Model):
    simulation_run = models.ForeignKey(SimulationRun, on_delete=models.CASCADE)
    name = models.CharField(max_length=5000)


class EventChangeStatMetric(models.Model):
    event_change_stat = models.ForeignKey(EventChangeStat, on_delete=models.CASCADE)
    name = models.CharField(max_length=5000)
    value_o = models.FloatField(null=True, blank=True)
    value_s = models.FloatField(null=True, blank=True)

pm2sim/templates/pm2sim/eventlog_confirm_delete.html
{% extends "base.html" %}

{% block content %}
	<div class="card w-96 bg-base-100 shadow-xl">
		<div class="card-body">
			<h2 class="card-title">Wirklich löschen?</h2>
			<p>Soll {{ object.name }} wirklich gelöscht werden?</p>

			<div class="card-actions justify-end">
				<a href="{% url "eventlogDetail" object.id %}" class="btn btn-success">Nein</a>
				<form method="post">{% csrf_token %}
					{{ form }}
					<button type="submit" class="btn btn-error">Ja</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

pm2sim/templates/pm2sim/eventlog_detail.html
{% extends 'base.html' %}
{% load orSkeleton %}
{% load deviation %}

{% block content %}
	<h1 class="text-4xl font-bold">{{ eventlog.name }}</h1>
	<p>{{ eventlog.number_of_cases|orSkeleton:10 }} verschiedene Fälle</p>
	<p>Start Activities: {{ eventlog.start_activities|orSkeleton:40 }}</p>
	<p>End Activities: {{ eventlog.end_activities|orSkeleton:40 }}</p>
	<a class="btn btn-secondary" href="{% url "analyseEventLog" eventlog.id %}">Original Eventlog analysieren</a>
	<a class="btn btn-secondary" href="{% url "simulateEventLog" eventlog.id %}">Simulieren</a>
	<a class="btn btn-error" href="{% url "deleteEventLog" eventlog.id %}">Löschen</a>

	{% if eventlog.process_img %}
		<div class="card shadow-xl mt-2">
			<div class="card-body">
				<h2 class="card-title">BPMN Model des originalen Event Logs</h2>
				<div class="card-actions justify-end">
					{% if eventlog.file %}
						<a class="btn btn-neutral" href="{{ eventlog.file.url }}" target="_blank">Download Event Log</a>
					{% endif %}
				</div>
			</div>
			<a href="{{ eventlog.process_img.url }}">
				<figure>
					<img src="{{ eventlog.process_img.url }}" alt="BPMN Model des originalen Event Logs">
				</figure>
			</a>
		</div>
	{% endif %}

	{% for sim_run in eventlog.simulationrun_set.all %}
		<div class="collapse collapse-arrow bg-base-200 mt-4">
			<input type="checkbox" />
			<div class="collapse-title text-xl font-medium">Simulationdurchlauf am {{ sim_run.timestamp }}</div>
			<div class="collapse-content">
				<p>Dauer: {{ sim_run.duration }} Sekunden</p>

				<a class="btn btn-secondary" href="{% url "analyseSimulatedEventLog" eventlog.id sim_run.id %}">
					Simulierten Eventlog analysieren
				</a>
				<a class="btn btn.error" href="{% url "deleteSimulationRun" sim_run.id %}">Löschen</a>
				{% if sim_run.simulated_process_img %}
					<div class="card shadow-xl mt-2">
						<div class="card-body">
							<h2 class="card-title">BPMN Model des simulierten Event Logs</h2>
							<div class="card-actions justify-end">
								{% if sim_run.simulated_event_log %}
									<a class="btn btn-neutral" href="{{ sim_run.simulated_event_log.url }}"
									   target="_blank">Download Generated Event Log</a>
								{% endif %}
							</div>
						</div>
						<a href="{{ sim_run.simulated_process_img.url }}">
							<figure>
								<img src="{{ sim_run.simulated_process_img.url }}"
								     alt="BPMN Model vom simulierten Event Log">
							</figure>
						</a>
					</div>
				{% endif %}

				{% if sim_run.event_times.all %}
					<div class="card shadow-xl mt-2">
						<div class="card-body">
							<h2 class="card-title">Dauer der einzelnen Events</h2>
							<table class="table table-zebra">
								<!-- head -->
								<thead>
								<tr>
									<th></th>
									<th>Name</th>
									<th>Durchschnittsdauer (Original)</th>
									<th>Durchschnittsdauer (Simuliert)</th>
									<th>Standardabweichung (Original)</th>
									<th>Standardabweichung (Simuliert)</th>
								</tr>
								</thead>
								<tbody>
								{% for event in sim_run.event_times.all %}
									<tr>
										<th>{{ index }}</th>
										<th>{{ event.name }}</th>
										<th>{{ event.mean_time_o|floatformat:"3g" }}</th>
										<th>{{ event.mean_time_s|floatformat:"3g" }}
											({% dev_perc event.mean_time_s event.mean_time_o %})
										</th>
										<th>{{ event.std_deviation_o|floatformat:"3g" }}</th>
										<th>{{ event.std_deviation_s|floatformat:"3g" }}
											({% dev_perc event.std_deviation_s event.std_deviation_o %})
										</th>
									</tr>
								{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				{% endif %}

				<div class="card shadow-xl">
					<div class="card-body">
						<h2 class="card-title">Zeit zwischen zwei Prozessdurchläufen</h2>
						<p>Durchschnitt: Original: {{ sim_run.start_time_mean_o|floatformat:"3g" }} | Simuliert:
							{{ sim_run.start_time_mean_s|floatformat:"3g" }}
							({% dev_perc sim_run.start_time_mean_s sim_run.start_time_mean_o %})</p>
						<p>Standardabweichung: Original: {{ sim_run.start_time_std_o|floatformat:"3g" }} | Simuliert:
							{{ sim_run.start_time_std_s|floatformat:"3g" }}
							({% dev_perc sim_run.start_time_std_s sim_run.start_time_std_o %})</p>
					</div>
				</div>

				{% if sim_run.eventchangestat_set.all %}
					<div class="card shadow-xl">
						<div class="card-body">
							<h2 class="card-title">Pfadwahrscheinlichkeiten</h2>
							<div class="collapse collapse-arrow bg-base-200 mt-4">
								<input type="checkbox" />
								<div class="collapse-title text-xl font-medium">Ausklappen</div>
								<div class="collapse-content">
									<ul>
										{% for event_change_stat in sim_run.eventchangestat_set.all %}
											<li>
												<strong>{{ event_change_stat.name }} -></strong>
												<ul>
													{% for metric in event_change_stat.eventchangestatmetric_set.all %}
														<li>
															<strong>{{ metric.name }}:</strong>
															Original: {{ metric.value_o|floatformat:"3g" }} |
															Simuliert: {{ metric.value_s|floatformat:"3g" }}
															({% dev_perc metric.value_s metric.value_o %})</p>
														</li>
													{% endfor %}
												</ul>
											</li>
										{% endfor %}
									</ul>
								</div>
							</div>
						</div>
					</div>
				{% endif %}

				{% if sim_run.evaluation_results %}
					{% for result in sim_run.evaluation_results.all %}
						<div class="card shadow-xl mt-2">
							<div class="card-body">
								<h2 class="card-title">Übereinstimmung des simulierten Event Logs mit dem originalen
									Prozess
									Modell</h2>
								<div class="flex flex-row gap-4">
									<div class="card shadow-xl">
										<div class="card-body">
											<h3 class="card-title">Alignment Analyse</h3>
											<div class="stats shadow">
												<div class="stat">
													<div class="stat-title">Präzession</div>
													<div class="stat-value">
														{{ result.al_sim_log_on_orig_mod_precision|floatformat }}</div>
													<div class="stat-desc">pro Prozess</div>
												</div>
												<div class="stat">
													<div class="stat-title">Passende Prozesse</div>
													<div class="stat-value">
														{{ result.al_sim_log_on_orig_mod_perc_fit_traces|floatformat }}</div>
													<div class="stat-desc">in %</div>
												</div>
												<div class="stat">
													<div class="stat-title">Prozess Alignment</div>
													<div class="stat-value">
														{{ result.al_sim_log_on_orig_mod_av_trace_fitness|floatformat }}</div>
													<div class="stat-desc">Durchschnittlich</div>
												</div>
											</div>
										</div>
									</div>
									<div class="card shadow-xl">
										<div class="card-body">
											<h3 class="card-title">Token Replay Analyse</h3>
											<div class="stats shadow">
												<div class="stat">
													<div class="stat-title">Präzession</div>
													<div class="stat-value">
														{{ result.tr_sim_log_on_orig_mod_precision|floatformat }}</div>
													<div class="stat-desc">pro Prozess</div>
												</div>
												<div class="stat">
													<div class="stat-title">Passende Prozesse</div>
													<div class="stat-value">
														{{ result.tr_sim_log_on_orig_mod_perc_fit_traces|floatformat }}</div>
													<div class="stat-desc">in %</div>
												</div>
												<div class="stat">
													<div class="stat-title">Prozess Alignment</div>
													<div class="stat-value">
														{{ result.tr_sim_log_on_orig_mod_av_trace_fitness|floatformat }}</div>
													<div class="stat-desc">Durchschnittlich</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="card shadow-xl mt-2">
							<div class="card-body">
								<h2 class="card-title">Übereinstimmung des originalen Event Logs mit dem simulierten
									Prozess
									Modell</h2>
								<div class="flex flex-row gap-4">
									<div class="card shadow-xl">
										<div class="card-body">
											<h3 class="card-title">Alignment Analyse</h3>
											<div class="stats shadow">
												<div class="stat">
													<div class="stat-title">Präzession</div>
													<div class="stat-value">
														{{ result.al_orig_log_on_sim_mod_precision|floatformat }}</div>
													<div class="stat-desc">pro Prozess</div>
												</div>
												<div class="stat">
													<div class="stat-title">Passende Prozesse</div>
													<div class="stat-value">
														{{ result.al_orig_log_on_sim_mod_perc_fit_traces|floatformat }}</div>
													<div class="stat-desc">in %</div>
												</div>
												<div class="stat">
													<div class="stat-title">Prozess Alignment</div>
													<div class="stat-value">
														{{ result.al_orig_log_on_sim_mod_av_trace_fitness|floatformat }}</div>
													<div class="stat-desc">Durchschnittlich</div>
												</div>
											</div>
										</div>
									</div>
									<div class="card shadow-xl">
										<div class="card-body">
											<h3 class="card-title">Token Replay Analyse</h3>
											<div class="stats shadow">
												<div class="stat">
													<div class="stat-title">Präzession</div>
													<div class="stat-value">
														{{ result.tr_orig_log_on_sim_mod_precision|floatformat }}</div>
													<div class="stat-desc">pro Prozess</div>
												</div>
												<div class="stat">
													<div class="stat-title">Passende Prozesse</div>
													<div class="stat-value">
														{{ result.tr_orig_log_on_sim_mod_perc_fit_traces|floatformat }}</div>
													<div class="stat-desc">in %</div>
												</div>
												<div class="stat">
													<div class="stat-title">Prozess Alignment</div>
													<div class="stat-value">
														{{ result.tr_orig_log_on_sim_mod_av_trace_fitness|floatformat }}</div>
													<div class="stat-desc">Durchschnittlich</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
				{% endif %}
			</div>
		</div>
	{% endfor %}
{% endblock %}

<div class="w-40 w-10 skeleton h-4 hidden">Tailwind workaround</div>

pm2sim/templates/pm2sim/eventlog_form.html
{% extends 'base.html' %}

{% block content %}
	<form method="post" enctype="multipart/form-data">
	{%  csrf_token %}
		{{ form }}
		<button class="btn btn-primary" type="submit">Speichern</button>
	</form>
{% endblock %}

pm2sim/templates/pm2sim/eventlog_list.html
{% extends "base.html" %}

{% block content %}
	<a class="btn" href="{% url 'createEventLog' %}">Neuen erstellen</a>
	<ul>
{% for eventlog in object_list %}
	<li>{{ eventlog.name }}<a class="btn" href="{% url 'eventlogDetail' eventlog.id %}">Details</a></li>
{% empty %}
	<li>Keine Event Logs verfügbar</li>
{% endfor %}
	</ul>
{% endblock %}

pm2sim/templates/pm2sim/simulationrun_confirm_delete.html
{% extends "base.html" %}

{% block content %}
	<div class="card w-96 bg-base-100 shadow-xl">
		<div class="card-body">
			<h2 class="card-title">Wirklich löschen?</h2>
			<p>Soll {{ object.name }} wirklich gelöscht werden?</p>

			<div class="card-actions justify-end">
				<a href="{% url "eventlogList" %}" class="btn btn-success">Nein</a>
				<form method="post">{% csrf_token %}
					{{ form }}
					<button type="submit" class="btn btn-error">Ja</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}